### ISSUE TITLE
Global session tests fail when different types of sessions are used

### ISSUE THREAD

**Issue by mantzouratos** [Tubular/sparkly#48] opened 2017-07-23 02:50 UTC
`SparklyGlobalSessionTest` can't currently support different types of sessions within the same project as metastore ownership doesn't seem to be handed around cleanly:
```
ERROR XSDB6: Another instance of Derby may have already booted the database /opt/sparkly/metastore_db.
```

To reproduce:
```
from unittest import TestCase

from sparkly.session import SparklySession
from sparkly.testing import SparklyGlobalSessionTest


class TestSparklyGlobalSessionRestart(TestCase):
    def test_restarting_global_session_with_different_type(self):
        class SessionA(SparklySession):
            pass


        class MyTestSessionA(SparklyGlobalSessionTest):
            session = SessionA


        class SessionB(SparklySession):
            pass


        class MyTestSessionB(SparklyGlobalSessionTest):
            session = SessionB


        MyTestSessionA.setUpClass()
        MyTestSessionA.spark.createDataFrame([('hi',)])#.write.saveAsTable('a')

        MyTestSessionB.setUpClass()
        MyTestSessionB.spark.createDataFrame([('dawg',)])#.write.saveAsTable('b')
```

**Comment by skliarpawlo** [comment] 2017-07-23 06:22
@mantzouratos did you forgot to call classTearDown()? Otherwise it's understandable that it errors, as you are trying to run two spark contexts simultaneously.

**Comment by skliarpawlo** [comment] 2017-07-23 06:41
However able to reproduce:
```
from unittest import TestCase

from sparkly.session import SparklySession
from sparkly.testing import SparklyGlobalSessionTest

class SessionA(SparklySession):
    pass

class SessionB(SparklySession):
    pass

class MyTestSessionA(SparklyGlobalSessionTest):
    session = SessionA

    def test_a(self):
        pass


class MyTestSessionB(SparklyGlobalSessionTest):
    session = SessionB

    def test_b(self):
        pass
```

Looks like line: `cls.spark.catalog.clearCache()` is problematic

**Comment by drudim** [comment] 2017-07-24 14:32
@mantzouratos try to use https://github.com/Tubular/sparkly/compare/feature/instant-interactive-testing#diff-19552fca8a5c6dcdc8a70aff90282776R75
should fix your problem.

**Comment by drudim** [comment] 2017-08-03 07:33
Fixed in https://github.com/Tubular/sparkly/releases/tag/v2.2.0

**Closed by drudim** 2017-08-03 07:33 UTC
Labels: bug
